### ISSUE TITLE
Publish CC Data In salesforce-export.csv

### ISSUE THREAD

**Issue by feanil** [openedx/openedx-webhooks#207]
See https://github.com/openedx/openedx-webhooks/issues/200 and https://github.com/openedx/openedx-webhooks/issues/227 for some background.

Things we probably need to do as a part of this work:

- [ ] Add a new fields to salesforce to track CC related data.
    - [ ] CCs are tracked at the repo level and at the org level so we may need both but might be able to get away with just the repo field to start with.
- [ ] Add/Update documentation around addition and removal of CCs and what to do in salesforce at those times.
- [ ] Update the export so that the new fields are being publish to the CSV.
- [ ] Update `openedx-webhooks` to pull this new data from the CSV.
- [ ] Update `openedx-webhooks` to pull org data from the CSV and drop reading data from orgs.yaml
- [ ] Add back core-contributor-specific OSPR bot comments. This feature was removed in #251, since the OSPR bot was relying on an outdated data source (people.yaml) to leave such comments.
- [ ] Remove the people.yaml and orgs.yaml files from  the `openedx-webhooks-data` repo.
- [ ] Figure out if we still need `repo-tools-data-schema` and update it as necessary to work with the new data setup.
    - With validation happening in salesforce we may not need `repo-tools-data-schema`.

**Comment by feanil** [comment]
We still need this to fully cleanup our reliance on  the old `people.yaml` file.  We could also just remove this feature from the bot but one of those two things needs to happen still.

**Comment by kdmccormick** [comment]
@nedbat removed our reliance on people.yaml in https://github.com/openedx/openedx-webhooks/pull/251, and by necessity removed all the core-contributor-aware features (notably: special PR comments for CCs) that depended on people.yaml.

If we implement this ticket, we'll need to put those CC PR comments back. I updated the task list in the ticket's description.

**Comment by kdmccormick** [comment]
I broke the remaining parts of this out into: https://github.com/openedx/openedx-webhooks/issues/312
