### ISSUE TITLE
Add a maintenance Label to all Repos so that we can tag maintenance work that needs to be done.

### ISSUE THREAD

**Issue by feanil** [openedx/openedx-webhooks#215]

**Comment by feanil** [comment]
Created https://github.com/openedx/terraform-github/pull/44 for the automation for this.

**Comment by nedbat** [comment]
The bot already makes the labels consistent across repos: https://github.com/openedx/openedx-webhooks-data/blob/main/labels.yaml

**Comment by feanil** [comment]
@nedbat it seemed like that bot would only make labels on repos that have webhooks triggered on them for PRs and I wasn't sure if it would create them on repos that have not had PRs, did I mis-read that?

**Comment by nedbat** [comment]
No, you are right about that.

**Comment by feanil** [comment]
This is done every repo in `openedx` now has a `🛠️ maintanance` label.
